### ISSUE TITLE
Running the script [python evaluate.py xxx] got wrong

### ISSUE THREAD

**Issue by qzcmask** [skumra/robotic-grasping#10]
Hello, I have some problems.

When I run the script:

`python evaluate.py --network ./output/models/200701_1113_training_cornell/epoch_47_iou_0.88 --dataset cornell --dataset-path ./datasets/cornell --iou-eval --use-depth 1 --use-rgb 1`

it will occur an error:
![image](https://user-images.githubusercontent.com/28850233/86219158-6159bd80-bbb4-11ea-92db-c444425d941f.png)

But When I change the parameter, it can ran:

`python evaluate.py --network ./output/models/200701_1113_training_cornell/epoch_47_iou_0.88 --dataset cornell --dataset-path ./datasets/cornell --iou-eval --use-depth 1 --use-rgb 0`

**How can I solve this problem? It seems that it only can use the depth information to evaluate.**

**In addition, if possible, can you upload the newest code?**

Thank you very much.

**Comment by skumra** [comment]
Is the model you are trying to evaluate trained on 4-channel input as well, i.e. using the parameters  `--use-depth 1 --use-rgb 1`?

**Comment by qzcmask** [comment]
Ok, I found I have not trained the model on 4-channel format.


Thank you, I will give a new try.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sulabh Kumra"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 凌晨4:33
收件人:&nbsp;"skumra/robotic-grasping"<robotic-grasping@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [skumra/robotic-grasping] Running the script [python evaluate.py xxx] got wrong (#10)





 
Is the model you are trying to evaluate trained on 4-channel input as well, i.e. using the parameters  --use-depth 1 --use-rgb 1?

**Comment by wangxiaojuan126** [comment]
Hello, I have some problems.
When I run the script:
python evaluate.py  --network <Path to Trained Network> When I add path：default='logs/211128_1809_training_jacquard/epoch_00_iou_0.00
have this false：FileNotFoundError: [Errno 2] No such file or directory: 'l'
can you help me and  tell me true path ?
thanks
@qzcmask
