### ISSUE TITLE
About Depth 

### ISSUE THREAD

**Issue by HLu97** [skumra/robotic-grasping#13]
In image.py, I find “img[r, c] = np.sqrt(x ** 2 + y ** 2 + z ** 2)” .
As far as I know, the depth value in the pcd file should be "z“.
In the final version, does the extraction of depth information not use ”z“ but ”sqrt(x ** 2 + y ** 2 + z ** 2)“? And why?
Hope you can answer, thank you!

**Comment by skumra** [comment]
Simply using the Z won't give the true depth value. That's why we calculate the euclidean distance between the camera and the point using: `np.sqrt(x ** 2 + y ** 2 + z ** 2)`
