### ISSUE TITLE
generate_cornell_depth

### ISSUE THREAD

**Issue by nickhward** [skumra/robotic-grasping#38]
When I run the command:  python -m utils.dataset_processing.generate_cornell_depth /Cornel_Grasping_dataset/archive

This is was I get: 

> (venv) nicholasward2@nicholasward2-Alienware-Aurora-R7:~/robotic-grasping$ python -m utils.dataset_processing.generate_cornell_depth /Cornel_Grasping_dataset/archive
> Matplotlib is building the font cache; this may take a moment.

Then it stops running immediately. Does anyone have any suggestions on how to fix this issue?

**Comment by nickhward** [comment]
I figured out that I just wasn't writing the path correctly. I just copied the absolute path from properties. Also in case anyone is having issues with finding the Cornell data-set because the link on GitHub repo no longer works you can find it here: https://www.kaggle.com/oneoneliu/cornell-grasp

**Comment by silver60229** [comment]
> 當我運行命令時： python -m utils.dataset_processing.generate_cornell_depth /Cornel_Grasping_dataset/archive
> 
> 這是我得到的：
> 
> > (venv) nicholasward2@nicholasward2-Alienware-Aurora-R7:~/robotic-grasping$ python -m utils.dataset_processing.generate_cornell_depth /Cornel_Grasping_dataset/archive 
> > Matplotlib 正在構建字體緩存；這可能需要一點時間。
> 
> 然後就立即停止運行。有沒有人對如何解決問題有任何建議？

Can I ask you for the complete usage method? For example, enter python -m utils.dataset_processing.generate_cornell_depth "path" in the robotic-grasping-master folder in "cmd"? Thank you

**Comment by zhenjing** [comment]
copy ./utils/dataset_processing/generate_cornell_depth.py  ./

modify generate_cornell_depth.py:
pcds = glob.glob(os.path.join(args.path, '*', 'pcd*[0-9].txt')) => pcds = glob.glob(os.path.join(args.path, 'pcd*[0-9].txt'))

other way:  recursive search all subdir
pcds = glob.glob(os.path.join(args.path, '**', 'pcd*[0-9].txt'), recursive=True)
