### ISSUE TITLE
Camera Calibration Issue

### ISSUE THREAD

**Issue by Nayoung-Oh** [skumra/robotic-grasping#39]
Hello! First, thanks for providing this wonderful repository!

While trying to reproduce the result with a physical robot, I think I found minor issues in the camera calibration part (the calibration does not work well for me...).
In the provided camera_calibration.py file, it calculates the transformation matrix from camera to robot using inv(self.robot2camera)
`camera_pose = np.linalg.inv(self.world2camera)`

However, I think it is not valid when the translation part (t) exists.
Therefore, I little bit modified the calibration method by calculating camera to robot transformation matrix directly and it worked well in my case.
`R, t = self._get_rigid_transform(np.asarray(self.measured_pts), np.asarray(new_observed_pts))`
(Also, modified calculating calibration error)

Could you explain what I misunderstood from the original calibration file or is my approach valid for the camera calibration?

Thanks for in advance.

**Comment by skumra** [comment]
If I understand your approach correct, I think it makes sense.

There were definitely some changes made during robot experiments that didn't get committed to this repository.

Please feel free to create a pull request to contribute your proposal to the repository.
