### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by dougsm** [skumra/robotic-grasping#4]
G'day @skumra 

Super awesome to see you making use of the GG-CNN project!  I'm curious to try out some of architecture changes you've made :-)

I just wanted to point out that the GG-CNN project is licenced under the BSD-3 licence.  This is a super permissive licence that basically lets you do anything you want (yay!), on the proviso that the original copyright notice and licence are copied along with the redistribution.  As such, can you please include the original BSD licence with the copied files.  

Also, I'd like to encourage you to consider a more permissive licence like MIT or BSD.  From a research point of view, the parasitic nature of GPL makes using your code in future work much more difficult.

**Comment by skumra** [comment]
Thank you for your interest in the research work and the recommendations. I will update the licence and include the original BSD licence with the copied files.
