### ISSUE TITLE
Availability of pretrained models

### ISSUE THREAD

**Issue by sallogy** [skumra/robotic-grasping#5]
Hi Sulabh,

great work, congratulations! Can you please make available the prettained model cornell_rgbd_iou_0.96 which is referred in run_grasp_generator.py.

Thanks,
György Salló

**Comment by skumra** [comment]
Hi György,

Thank you for the interest in our research. We will be uploading a bunch of good pre-trained models once the review process of our paper is complete.

You can also use the `train_network.py` to train a new model yourself.

Thanks,
Sulabh

**Comment by sallogy** [comment]
Hi Sulabh,

thanks for the fast response. What do you expect, when the review process will be finished? I will try to train the model myself - can you tell me what GPU resources are needed, and approximately how long it will take?

Thanks,
György

**Comment by skumra** [comment]
We expect the review process to be completed by June 30, 2020. Given the light weight nature of GR-ConvNet, you can train the model within a few hours using a decent Nvidia GPU. You can also train on a CPU but it may up to a day to train. Also, training the model using only depth data will be a lot faster.

**Comment by sallogy** [comment]
Hi Sulabh,

thank you for the info.

**Comment by wassname** [comment]
@skumra , thanks for sharing the code. Now the review process is completed, could you please uploaded the pretrained models if you still have them.
