### ISSUE TITLE
Trained network, poor results

### ISSUE THREAD

**Issue by sallogy** [skumra/robotic-grasping#6]
Hi Sulabh,

I managed to train the network on the Cornell dataset with the default settings (only on depth images) and the best accuracy obtained was 88%.  I have seen in your paper that you obtained best accuracy of 95.4%.
Do you have any suggestions, ideas how can I improve the accuracy beside using the RGB images? How much the accuracy should improve if I use the RGB images as well?
Additionally, I tried to run the run_offline.py  inference script on the model I just trained, using only depth - it gave me an error. I inspected the code, it seemed that the batch dimension was missing, I added it with unsqueeze.
Now the program ran successfully, but the results are poor on random pictures - scores around 0.1, grasp points outside the objects. Do you have any idea what could go wrong? Maybe the format of the pictures is different than during training?

Thanks,
György

**Comment by skumra** [comment]
Hi György,

The default parameters are set to give decent results on different modalities and datasets. We are working on a journal paper which will discuss in details about these hyper parameters and how to set them to get the best results.

It is possible that `run_offline.py` is outdated as it was created as an initial debugging tool. I recommend using `run_realtime.py` for running this on a robotic system.

I m not sure by what you mean by results on random images. I will recommend starting by analyzing the model output on Cornell dataset. Which camera and format are you using?

Thanks,
Sulabh

**Comment by sallogy** [comment]
Hi Sulabh,

sorry for responding a little bit late. I ment by random images randomly selected  depth images from the Cornell dataset. I'm still waiting for my Realsense D435 camera to arrive. I the meantime, I ran evaluate.py on the trained model, and the results seemed quite good, so probably run_offline.py is really outdated.  Studying the code, I have a question:  in camera_data.py, you add the batch dimension for RGB and Depth, for RGB only, but not for Depth only (lines 73-84).  What if I try to run prediction on the model in run_realtime.py with only depth images, batch dimension missing - this should not be a problem? Or am I getting something wrong?

Hope you are well, take care
György
