### ISSUE TITLE
no file

### ISSUE THREAD

**Issue by SHYang1210** [skumra/robotic-grasping#7]
hi, I am very interested in your work, but I met the following error while training the network, looking forward to your help.
FileNotFoundError: No such file: '/home/aistudio/robotic/dataset/01/pcd0151d.tiff'。
I found that the downloaded dataset does not have a .tiff file。

**Comment by skumra** [comment]
You need to generate the `.tiff` files using the utils provided. For the Cornell data set, you can convert the PCD files to depth images by running:
`python -m utils.dataset_processing.generate_cornell_depth <Path To Dataset>`

**Comment by SHYang1210** [comment]
I'm sorry, I responded to your message late, and now I can convert the depth data and have completed the training. But my evaluation keeps showing the loading path error, can you give an example of loading for the evaluation? Thank you.

**Comment by skumra** [comment]
You can run evaluation using `evaluate.py`. For example: 
```
python evaluate.py --network <Path to Trained Network> --dataset cornell --dataset-path <Path to Dataset> --iou-eval
```

**Comment by SHYang1210** [comment]
I'm sorry to bother you again. For evaluation, I can't always load to the correct network path. I loaded the network from the output model. For questions, you can give the correct Path to Trained Network. thank you very much

**Comment by zpy863** [comment]
Where to find the saved file after running the evaluation.py
